import {z} from 'zod';

import tasks from './tasks.json';
import type {Status, Priority} from './dto/Task';
import {statuses, priorities} from './dto/Task';
import {DEFAULT_STATUS, DEFAULT_PRIORITY} from './constants';


const taskSchema = z.object({
  id: z.number(),
  title: z.string(),
  description: z.string().optional(),
  createdAt: z.string(),
  completedAt: z.string().optional(), 
  status: z.enum(statuses).default(DEFAULT_STATUS),
  priority: z.enum(priorities).default(DEFAULT_PRIORITY),
  deadline: z.string().optional(),
});

const tasksSchema = z.array(taskSchema);

type Task = z.infer<typeof taskSchema>;

type AutoGeneratedFields = 'id' | 'createdAt';
type FieldsWithDefaults = 'status' | 'priority';
type CreateTaskSettings = Omit<Task, AutoGeneratedFields | FieldsWithDefaults> & Partial<Pick<Task, FieldsWithDefaults>>;

const parsedTasks: Task[] = tasksSchema.parse(tasks);
console.log('Parsed Tasks:', parsedTasks);

//1. Функція для отримання деталей завдання за вказаним id
function getTaskDetails(id: number): Task | undefined  {
  // треба використати return!
  return parsedTasks.find((task) => task.id === id)
}

console.log('Test getTaskDetails(4):', getTaskDetails(4)); //{ id: 4, title: 'Create logo variants',...}
console.log('Test getTaskDetails(999):', getTaskDetails(999)); //undefined

//2. Функція створення нового завдання
function createNewTask (settings: CreateTaskSettings) : Task{
  const newId = Math.max(...parsedTasks.map(task => task.id)) + 1;
  const createdAt = new Date().toISOString();

    const newTask: Task = {
    id: newId,
    createdAt: createdAt,
    status: settings.status ?? DEFAULT_STATUS,
    priority: settings.priority ?? DEFAULT_PRIORITY,
    ...settings 
  };

  parsedTasks.push(newTask);
  return newTask;
}

const newTask = createNewTask({
  title: 'Моє нове завдання',
  description: 'Тестую функцію'
});
console.log('Створене завдання:', newTask); // { id: 11, createdAt: '2025-10-12T18:45:21.185Z', ...}
console.log('Всього завдань:', parsedTasks.length); // 11

//3. Функція апдейту деталей завдання
function updateTaskDetails(
  id: number, 
  updates: Partial<Omit<Task, 'id' | 'createdAt'>>
): Task | undefined {
  const taskIndex = parsedTasks.findIndex(t => t.id === id);
  
  if (taskIndex === -1) {
    return undefined;
  }
  
  const task = parsedTasks[taskIndex]!;
  
  const updatedTask: Task = {
    ...task,
    ...updates
  } 
  
  parsedTasks[taskIndex] = updatedTask;
  
  return updatedTask;
}

const updatedTask = updateTaskDetails(2, {
  status: "done",
  priority: "medium",
  completedAt: new Date().toISOString()
});
console.log('Оновлене завдання:', updatedTask); // { id: 2, ... status: 'done', priority: 'medium',... completedAt: '2025-10-12T18:46:51.474Z'}
 
//4. Функція видалення завдання
function deleteTaskDetails(id: number): boolean {
  const taskIndex = parsedTasks.findIndex(task => task.id === id);
  
  if (taskIndex === -1) {
    return false;
  }
  
  parsedTasks.splice(taskIndex, 1);
  
  return true;
}

console.log('Видалення завдання 3:', deleteTaskDetails(3)); // true

//5. Функція фільтрації завдань за статусом, датою створення та пріоритетом
function filterTasks(filters: {
  status?: Status;           
  priority?: Priority;       
  createdAfter?: string;     
  createdBefore?: string;    
}): Task[] {
  
  return parsedTasks.filter(task => {
    
    if (filters.status && task.status !== filters.status) {
      return false;  
    }
    
    if (filters.priority && task.priority !== filters.priority) {
      return false;
    }
    
    if (filters.createdAfter && task.createdAt < filters.createdAfter) {
      return false;  
    }
    
    if (filters.createdBefore && task.createdAt > filters.createdBefore) {
      return false;  
    }
    
    return true;
  });
}

console.log('Завдання зі статусом "done":', filterTasks({ status: 'done' }));
console.log('Високопріоритетні завдання:', filterTasks({ priority: 'high' }));
console.log('Завдання створені після 2024-10-03:', filterTasks({ createdAfter: '2024-10-03' }));


// перевірки, чи завершено завдання до дедлайну
function isTaskOnTime(id: number): boolean | null {
  const task = getTaskDetails(id);
  
  if (!task?.completedAt || !task.deadline) {
    return null;
  }

  return task.completedAt <= task.deadline;
}

console.log('Завдання 1 вчасно?', isTaskOnTime(1));  // true (2024-10-02 < 2024-10-05)
console.log('Завдання 2 вчасно?', isTaskOnTime(2));  // false (2025-10-12 > 2024-10-15)
console.log('Завдання 3 вчасно?', isTaskOnTime(3));  // null (ще не завершене)