export const statuses = ["todo", "inProgress", "done"] as const;
export type Status = typeof statuses[number];

export const priorities = ["low", "medium", "high"] as const;
export type Priority = typeof priorities[number];

export type Task = {
  id: number;
  title: string;
  description?: string;
  createdAt: string;
  completedAt?: string;
  status: Status;
  priority: Priority;
  deadline?: string;
};

export type AutoGeneratedFields = 'id' | 'createdAt';
export type FieldsWithDefaults = 'status' | 'priority';
export type CreateTaskSettings = Omit<Task, AutoGeneratedFields | FieldsWithDefaults> & 
  Partial<Pick<Task, FieldsWithDefaults>>;